---
- name: install node
  shell: |
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && sudo apt-get install -y nodejs

- name: Update npm to latest
  npm:
    name: npm
    state: latest # noqa 403
    global: true

- name: Install coffee-script & less packages
  npm:
    name: "{{ item }}"
    state: present
    global: true
  with_items:
    - less
    - coffee-script

- name: Install npm packages
  npm:
    path: "{{ rapidpro_checkout_path }}"
  ignore_errors: true
  become: true
  become_user: "{{ rapidpro_system_user }}"

- name: Install ona-oidc package
  become: true
  become_user: "root"
  pip:
    name: "git+https://github.com/onaio/ona-oidc.git@{{ rapidpro_oidc_version }}#egg=ona-oidc"
    state: present
    extra_args: "-e"
    virtualenv: "{{ rapidpro_venv_path }}"
    virtualenv_python: "{{ rapidpro_python_version }}"
  when: rapidpro_enable_oidc

- name: Override login and logout urls
  template:
    src: "templates/django_checkout_path/temba/templates/includes/nav.haml.j2"
    dest: "{{ rapidpro_checkout_path }}/templates/includes/nav.haml"
    owner: "{{ rapidpro_system_user }}"
    group: "{{ rapidpro_system_group }}"
    block_start_string: "[%"
    block_end_string: "%]"
    variable_start_string: "[{"
    variable_end_string: "}]"
    mode: "0644"
  when:
    - rapidpro_enable_oidc
    - rapidpro_oidc_login is not none
    - rapidpro_oidc_auth_server is not none
    - rapidpro_oidc_logout is not none

- name: Disable "Create account" form on public index
  template:
    src: "templates/django_checkout_path/temba/templates/public/public_index.haml.j2"
    dest: "{{ rapidpro_checkout_path }}/templates/public/public_index.haml"
    owner: "{{ rapidpro_system_user }}"
    group: "{{ rapidpro_system_group }}"
    block_start_string: "[%"
    block_end_string: "%]"
    variable_start_string: "[{"
    variable_end_string: "}]"
    mode: "0644"
  when: rapidpro_disable_home_create_account
