---
# Due to this bug https://github.com/npm/cli/issues/682
- name: Install n with npm for nodejs management
  npm:
    name: n
    state: latest  # noqa 403
    global: true

- name: Manage nodejs with n
  command: "n latest && /usr/local/bin/npm update --global npm"
  args:
    creates: /usr/local/bin/node

- name: Install coffeescript & less packages
  npm:
    name: "{{ item }}"
    state: present
    global: true
    executable: /usr/local/bin/npm
  register: _npm_output
  with_items:
    - less
    - coffeescript
  failed_when:
    - _npm_output.rc | default(0) != 0
    - "'EEXIST: file already exists' not in _npm_output.msg | default('')"

- name: Install npm packages
  npm:
    ci: true
    path: "{{ rapidpro_checkout_path }}"
    executable: /usr/local/bin/npm
  become: true
  become_user: "{{ rapidpro_system_user }}"

- name: Install ona-oidc package
  become: true
  become_user: "root"
  pip:
    name: "git+https://github.com/onaio/ona-oidc.git@{{ rapidpro_oidc_version }}#egg=ona-oidc"
    state: present
    extra_args: "-e"
    virtualenv: "{{ rapidpro_venv_path }}"
    virtualenv_python: "{{ rapidpro_python_version }}"
  when: rapidpro_enable_oidc

- name: Override login and logout urls
  template:
    src: "templates/django_checkout_path/temba/templates/includes/nav.haml.j2"
    dest: "{{ rapidpro_checkout_path }}/templates/includes/nav.haml"
    owner: "{{ rapidpro_system_user }}"
    group: "{{ rapidpro_system_group }}"
    block_start_string: "[%"
    block_end_string: "%]"
    variable_start_string: "[{"
    variable_end_string: "}]"
    mode: '0644'
  when:
    - rapidpro_enable_oidc
    - rapidpro_oidc_login is not none
    - rapidpro_oidc_auth_server is not none
    - rapidpro_oidc_logout is not none

- name: Disable "Create account" form on public index
  template:
    src: "templates/django_checkout_path/temba/templates/public/public_index.haml.j2"
    dest: "{{ rapidpro_checkout_path }}/templates/public/public_index.haml"
    owner: "{{ rapidpro_system_user }}"
    group: "{{ rapidpro_system_group }}"
    block_start_string: "[%"
    block_end_string: "%]"
    variable_start_string: "[{"
    variable_end_string: "}]"
    mode: '0644'
  when: rapidpro_disable_home_create_account
