---
- name: Converge
  hosts: all
  roles:
    - role: ANXS.postgresql
      vars:
        postgresql_users:
          - name: rapidpro
            pass: rapidpro
            encrypted: true
        postgresql_databases:
          - name: rapidpro
            owner: rapidpro
        postgresql_user_privileges:
          - name: rapidpro
            db: rapidpro
            priv: "ALL"
            role_attr_flags: "LOGIN"

    - role: DavidWittman.redis

    - role: ansible-rapidpro
      vars:
        rapidpro_postgresql_password: rapidpro
