---
- name: Converge
  hosts: all
  roles:
    - role: ANXS.postgresql
      vars:
        postgresql_users:
          - name: rapidpro
            pass: rapidpro
            encrypted: true
        postgresql_databases:
          - name: rapidpro
            owner: rapidpro

    - role: DavidWittman.redis

    - role: ansible-rapidpro
      vars:
        rapidpro_postgresql_password: rapidpro
